# Generated by Django 3.0 on 2020-07-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0003_auto_20200712_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzasize',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzaApp.Pizza'),
        ),
    ]
