# Generated by Django 3.0 on 2020-07-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0004_pizzasize_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzasize',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizzaSize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzaApp.PizzaImage'),
        ),
    ]
