# Generated by Django 3.0 on 2020-07-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0005_auto_20200712_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='pizzaSize',
        ),
        migrations.AddField(
            model_name='pizzasize',
            name='pizzaSize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzaApp.Pizza'),
        ),
    ]
