# Generated by Django 3.0 on 2020-07-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0007_auto_20200712_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza',
            new_name='pizzaSize',
        ),
    ]
