# Generated by Django 3.0 on 2020-07-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0008_auto_20200712_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzaimage',
            old_name='product',
            new_name='pizza',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pizzaSize',
        ),
        migrations.CreateModel(
            name='PizzaSizeRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzaApp.Pizza')),
                ('pizzaSize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzaApp.PizzaSize')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizzaSize',
            field=models.ManyToManyField(through='pizzaApp.PizzaSizeRel', to='pizzaApp.PizzaSize'),
        ),
    ]
