# Generated by Django 3.0 on 2020-07-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0010_auto_20200712_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(through='pizzaApp.OrderPizzaRel', to='pizzaApp.Pizza'),
        ),
        migrations.AlterField(
            model_name='orderpizzarel',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderPizza', to='pizzaApp.Pizza'),
        ),
    ]
