# Generated by Django 3.0 on 2020-07-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0011_auto_20200712_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizzarel',
            name='pizzasNumber',
            field=models.IntegerField(default=1),
        ),
    ]
