# Generated by Django 3.0 on 2020-07-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0012_auto_20200712_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizzarel',
            name='pizzasNumber',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
